---
- name: DB 패키지 삭제
  hosts: all
  gather_facts: no
  vars_files:
    - vars/db.yml
  tasks:
  - name: DB(yum) 패키지 삭제
    yum:
      name: "{{ pkg_db }}"
      state: absent
    notify:
    - set db init
  - name: DB 서비스 종료
    service:
      name: "{{ svc_db }}"
      state: stopped
      enabled: no

  
  